<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<head>
    <title>DoBoe HomeBuddy</title>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="keywords" content="" />

    <link media="all" rel="stylesheet" type="text/css" href="<?php echo App::getBaseUrl()?>skin/css/bootstrap.css" />
	<link media="all" rel="stylesheet" type="text/css" href="<?php echo App::getBaseUrl()?>skin/css/style.css" />
    <script src="<?php echo App::getBaseUrl()?>skin/js/bootstrap.bundle.min.js"></script>
</head>
<body>	
<div class="container-fluid vertical-center ">
  <div class="row ">
    <div class="col-md-4 offset-md-4 text-dark ">
		<div class="">
			Die Seite die du suchst ist leider nicht vorhanden.
		</div>
    </div>
  </div>
</div> 
</body>
</html>