<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">
  <!-- Header -->
  <header class="w3-container" style="padding-top:22px">
    <h5><b><i class="fa fa-dashboard"></i>Dashboard</b></h5>
  </header>

  <div class="w3-row-padding w3-margin-bottom dash">

      <a href="<?php echo App::getBaseUrl() ?>finanzen/haushaltskasse"> 
        <div class="w3-third dashbox bgDash1">    
          <div class="w3-container  w3-padding-16">
            <div class="left">
              Haushaltskasse: <br>
              Du bekommst noch: 
            </div>
            <div class="right">
              52 €
              <br>
              13 €
            </div>
          </div>  
          
        </div>
      </a>
      <a href="<?php echo App::getBaseUrl() ?>kueche/einkauf"> 
        <div class="w3-third dashbox bgDash3">    
          <div class="w3-container bgDash3 w3-padding-16">
            <div class="left">
              Einkauflisten vorhanden:
            </div>
            <div class="right">
              2
            </div>
          </div>      
        </div>
      </a> 
      <a href="<?php echo App::getBaseUrl() ?>finanzen/ausgaben"> 
        <div class="w3-third dashbox bgDash2">    
          <div class="w3-container bgDash2 w3-padding-16">
          <div class="left">
              Ausgaben Sarah:
              <br>
              Ausgaben Thomas:
            </div>
            <div class="right">
              4690,00 €
              <br>
              4672,96 €
            </div>
          </div>      
        </div>
      </a>
  </div>

  <div class="container-fluid" >
    Hello World
  </div>
</div>
<footer class="footer mt-auto py-3 bgTop" style="margin-left:0px !important">
    <div class="container">
      &nbsp
    </div>
</footer>
<!-- End page content -->
<!-- Begin Footer -->
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>