<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="container-fluid">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">wer</th>
          <th scope="col">wann</th>
          <th scope="col">wieviel</th>
          <th scope="col">stand</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">3</th>
          <td>Thomas</td>
          <td>4.1.21</td>
          <td>-27 €</td>
          <td>157 €</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>sarah</td>
          <td>2.1.21</td>
          <td>-16 €</td>
          <td>184 €</td>
        </tr>
        <tr>
          <th scope="row">1</th>
          <td>Thomas</td>
          <td>1.1.21</td>
          <td>+200 €</td>
          <td>200 €</td>
        </tr>
      </tbody>
    </table>
    <div>
      auswahl mona/ ahr
    </div>
  </div>
</div>

  <!-- Footer -->
  <footer class="footer mt-auto py-3 bgTop">
  <div class="container-fluid">
      <div class="right">
        <a href="" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          <i class="fas fa-plus-circle add lift w3-animate-bottom "></i>
        </a>       
      </div>

<!--       
        <i class="fas fa-plus-circle add lift w3-animate-bottom "></i>   
      -->

      <!-- Modal -->
      <div class="modal fade" style="position: relativ;" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog" >
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Understood</button>
            </div>
          </div>
        </div>
      </div>



  </div>
</footer>

<!-- End page content -->
<!-- Begin Footer -->
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>