<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="container-fluid paddingBottom">
    <div class="right py-2">
      <div class="w3-dropdown-click">
        <button onclick="getMonth()" class="btn btn-primary">Monat/Jahr</button>
        <div id="monat" class="w3-dropdown-content w3-bar-block w3-border text-center">
          <a href="<?php echo App::getBaseUrl()."/finanzen/haushaltskasse/"; ?>" class="w3-bar-item w3-button">-</a>
        <?php foreach (\Util\Datum::getDateRange() as $date): ?>
          <a href="<?php echo App::getBaseUrl()."/finanzen/haushaltskasse/datum/".$date->format('Y-m'); ?>" class="w3-bar-item w3-button"><?php echo $date->format('m/y')."\n";?></a>
        <?php endforeach; ?> 
        </div>
      </div>
    </div>
     <?php /**var_dump($data); */?>  
    <table class="table table-striped mb-0 text-center">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Wer</th>
          <th scope="col">Wann</th>
          <th scope="col">+/-</th>
          <th scope="col">Stand</th>
        </tr>
      </thead>
      <tbody>
      <?php $i=count($data)+1; foreach ($data as $ausgabe): $i--;?>
        <tr>
          <th scope="row"><?php /* echo */ $ausgabe->getId(); echo $i;?></th>
          <td><?php echo $ausgabe->getWer(); ?></td>
          <td><?php echo date("d.m.y",strtotime($ausgabe->getDatum())); ?></td>
          <td><?php echo $ausgabe->getWieviel(); ?> &#8364;</td>
          <td><?php echo $ausgabe->getStand(); ?> &#8364;</td>
        </tr>
        <?php endforeach; ?>
      </tbody>      
    </table> 
  </div>
</div>
<!-- End page content -->

<!-- Footer -->

<!-- Link und auswahl zur doppel child modal mit versch. Formularen
 -->
<!-- Modal -->
<footer class="footer mt-auto py-3 bgTop">
<div class="container-fluid">
      <div class="right">
        <a href="#add" data-target="#id" data-toggle="modal" class="lift" onclick="document.getElementById('choose').style.display='block'">
          <i class="fas fa-plus-circle add lift"></i>
        </a>       
      </div>
      <div id="choose" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content w3-card-4 w3-animate-zoom">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Haushaltskasse</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('choose').style.display='none'"></button>
                </div>
                <div class="modal-body">
                <div class="text-center">Abrechnen oder pers. Konto ausgleichen?
                  <div class="row justify-content-md-center">
                      <div class="col p-5">
                        <a href="#add" data-target="#id" data-toggle="modal" class="" onclick="document.getElementById('add').style.display='block'" onmouseup="document.getElementById('choose').style.display='none'">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/out.png" alt="abrechnen" class="img-fluid" >
                        </a>                        
                      </div>
                      <div class="col p-5">
                        <a href="#add" data-target="#id" data-toggle="modal" class="" onclick="document.getElementById('balance').style.display='block'" onmouseup="document.getElementById('choose').style.display='none'">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/money-transfer.png" alt="einzahlen"  class="img-fluid" >
                        </a>                          
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </div>
      <div id="balance" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content w3-card-4 w3-animate-zoom">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Haushaltskasse</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('balance').style.display='none'"></button>
                </div>
                <div class="modal-body">
                <div class="text-center">ausgleichen?
                  <div class="justify-content-md-center">
                    Aktueller Stand: xx <br>
                    Du kannst dir max. xx € aus der kasse nehmen<br>
                    du musst xx einzahlen
                    <!-- echo aus methode -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </div>



      <div id="add" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content w3-card-4 w3-animate-zoom">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Haushaltskasse</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('add').style.display='none'"></button>
                </div>
                <div class="modal-body">
                <form id="addForm" class="addForm" method="POST">
                  <input type="hidden" name="wer" value="<?php echo $_SESSION['user_name']; ?>">
                  
                  <!-- One "tab" for each step in the form: -->
<!--                   <div class="tab text-center">Abrechnen oder pers. Konto ausgleichen?
                    <div class="row justify-content-md-center">
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="inorout" id="abr" value="-" checked required >
                      <label for="abr">
                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/out.png" alt="abrechnen" class="img-fluid" >
                      </label>
                      </div>
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="inorout" id="einz" value="+">
                      <label for="einz">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/money-transfer.png" alt="einzahlen"  class="img-fluid" >
                      </label>
                      </div>
                    </div>
                  </div> -->
                  <div class="tab">Wann:
                    <p><input type="date" name="datum" class="form-control" value="<?php echo date("Y-m-d"); ?>" required></p>
                  </div>
                  <div class="tab">Wieviel:
                    <p><input type="number" name="wieviel" step="0.5" placeholder="  €" class="form-control" required></p>    
                    <p>Womit bezahlt?</p> 
                    <div>
                      <input type="radio" id="porte" name="womit" value="self" checked>
                      <label for="porte">eigenes Geld?</label>
                    </div>
                    <div>
                      <input type="radio" id="kasse" name="womit" value="kasse">
                      <label for="kasse">Haushaltskasse?</label>
                    </div>              
                  </div>
                  <div class="tab">Private Einkäufe he­r­aus­rech­nen?:
                    <p><input type="number" name="privat" step="0.5" placeholder="€" class="form-control" ></p>              
                  </div>
                  <div class="tab">wo warst du einkaufen?
                    <div class="row justify-content-md-center">
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="wo" id="bae" value="1" >
                      <label for="bae">
                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/bakery.png" alt="Baecker" class="img-fluid" >
                      </label>
                      </div>
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="wo" id="fle" value="2">
                      <label for="fle">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/wurst.png" alt="Fleischer" class="img-fluid" >
                      </label>
                      </div>
                    </div>
<!--                     <div class="row">
                      <div>
                        <input type="text" name="wo" class="form-control" >
                      </div>
                    </div> -->
                  </div>
                  <!-- Circles which indicates the steps of the form: -->
                  <div style="text-align:center;margin-top:40px;">
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span> 
                  </div>
                  <hr>
                  <div style="overflow:auto;">
                    <div style="float:right;">
                    <button type="button" class="btn btn-secondary" id="prevBtn" onclick="nextPrev(-1)">back</button>
                    <button type="button" class="btn btn-primary" id="nextBtn" onclick="nextPrev(1)">Next</button>
                    </div>
                  </div>
                </form> 
                </div>
              </div>
            </div>

      </div>
</footer>
<!-- Begin script area -->
<script src="<?php echo App::getBaseUrl() ?>/skin/js/form.js"></script>
<script src="<?php echo App::getBaseUrl() ?>/skin/js/script.js"></script>
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>