<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="container-fluid paddingBottom">
    <div class="right py-2">
      <div class="w3-dropdown-click">
        <button onclick="getMonth()" class="btn btn-primary">Monat/Jahr</button>
        <div id="monat" class="w3-dropdown-content w3-bar-block w3-border">
          <a href="<?php echo App::getBaseUrl()."/finanzen/ausgaben/"; ?>" class="w3-bar-item w3-button">-</a>
        <?php foreach (\Util\Datum::getDateRange() as $date): ?>
          <a href="<?php echo App::getBaseUrl()."/finanzen/ausgaben/datum/".$date->format('Y-m'); ?>" class="w3-bar-item w3-button"><?php echo $date->format('m/y')."\n";?></a>
        <?php endforeach; ?> 
        </div>
      </div>
    </div>
    <?php /* var_dump($data); */ ?>
    <table class="table table-striped mb-0 text-center">
      <thead>
        <tr>
          <th scope="col">Wann</th>
          <th scope="col">Wer</th>
          <th scope="col">Kategorie</th>
          <th scope="col">Wieviel</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach ($data as $ausgabe): ?>
        <tr>
          <td><?php $ausgabe->getID(); echo date("d.m.y",strtotime($ausgabe->getDatum())); ?></td>
          <td><?php echo $ausgabe->getWer(); ?></td>
          <td><?php echo $ausgabe->getKategorie(); ?></td>
          <td><?php echo $ausgabe->getWieviel(); ?> &#8364;</td>
        </tr>
        <?php endforeach; ?>
      </tbody>      
    </table>
    <nav aria-label="kasse" class="py-3">
      <ul class="pagination pagination-sm justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- End page content -->
<!-- Footer -->
<!-- Modal -->
<footer class="footer mt-auto py-3 bgTop">
<div class="container-fluid">

      <div class="right">
        <a href="#add" data-target="#id" data-toggle="modal" class="lift" onclick="document.getElementById('add').style.display='block'">
          <i class="fas fa-plus-circle add lift"></i>
        </a>       
      </div>
      <div id="add" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content w3-card-4 w3-animate-zoom">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">allg. Ausgaben</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('add').style.display='none'"></button>
                </div>
                <div class="modal-body">
                <form id="addForm" class="addForm" method="POST">
                  <input type="hidden" name="wer" value="<?php echo $_SESSION['userName']; ?>">
                  
                  <!-- One "tab" for each step in the form: -->
                  <div class="tab">Wann?
                    <p><input type="date" name="datum" class="form-control" value="<?php echo date("Y-m-d"); ?>" required></p>
                      Wieviel?
                    <p><input type="number" name="wieviel" step="0.5" placeholder="  €" class="form-control" required></p>         
                  </div>
                  <div class="tab">
                    <p>
                      <select name="kategorie" id="kategorie" class="form-select" required>
                          <option selected disabled >Kategorie w&auml;hlen</option>
                          <option value="Wohnung">Wohnung</option>
                          <option value="Baumarkt">Baumarkt</option>
                          <option value="Auto">Auto</option>
                          <option value="Geschenke">Geschenke</option>
                          <option value="Freizeit">Freizeit</option>
                          <option value="Urlaub">Urlaub</option>
                          <option value="Genuss">Genuss</option>
                          <option value="sonstiges" required >sonstiges</option>
                      </select>
                    </p>
                    <p>
                    <textarea name="kommentar" id="kommentar" class="form-control" rows="4" placeholder="Kommentar zur Ausgabe"></textarea>
                    </p>
                  </div>
                  <!-- Circles which indicates the steps of the form: -->
                  <div style="text-align:center;margin-top:40px;">
                    <span class="step"></span>
                    <span class="step"></span>
                  </div>
                  <hr>
                  <div style="overflow:auto;">
                    <div style="float:right;">
                    <button type="button" class="btn btn-secondary" id="prevBtn" onclick="nextPrev(-1)">back</button>
                    <button type="button" class="btn btn-primary" id="nextBtn" onclick="nextPrev(1)">Next</button>
                    </div>
                  </div>
                </form> 
                </div>
              </div>
            </div>

      </div>
</footer>
<!-- Begin script area -->
<script src="<?php echo App::getBaseUrl() ?>/skin/js/form.js"></script>
<script src="<?php echo App::getBaseUrl() ?>/skin/js/script.js"></script>
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>