<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="container-fluid paddingBottom">
    <!-- <div class="w3-row"> -->
      <div class="w3-col m4 l4 py-2">
        <div class="">
          <div>Kassenstand am Monatsende</div>
          <canvas id="sumMonth" class="shadow-sm m-1"></canvas>
        </div>
      </div>
      <div class="w3-col m4 l4 py-2">
        <div class="">
          <div>Ausgaben kategorisiert</div>
          <canvas id="sumByKat"  class="shadow-sm m-1"></canvas>
        </div>
      </div>
      <div class="w3-col m4 l4 py-2">
        <div class="">
        <div>Momentaner Tagesstand im verhältnis zum Tagesdurchschnitt Gesamt</div>
        <!-- <canvas id="sumByKat" class="shadow-sm m-1"></canvas> -->
      </div>
      </div>
    <!-- </div> -->
  </div>
  <div class="w3-row-padding paddingBottom">
    <h3>Wie wäre es heute mit ...</h3>
    <div class="w3-col m4 l4 py-2">
      <div class="card h-200 shadow-sm">
        <img src="https://www.kochtrotz.de/wp-content/uploads/2021/04/ofen-spitzkohl-5-2-300x200.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
    <div class="w3-col m4 l4 py-2">
      <div class="card h-200 shadow-sm">
        <img src="https://www.wunderkessel.de/media/leckerer-klossauflauf.18618/full?lightbox=1&last_edit_date=0" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
    <div class="w3-col m4 l4 py-2">
      <div class="card h-200 shadow-sm">
        <img src="https://images.lecker.de/come-together-gulasch-f10486301,id=a2f0dcca,b=lecker,w=590,h=442,cg=c.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
  </div>
</div>
<footer class="footer mt-auto py-3 bgTop ">
    <div class="container">
      &nbsp
    </div>
</footer>
<!-- End page content -->
<!-- Begin Footer -->
<!-- Begin script area -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
const sbk = document.getElementById('sumByKat');
const sM = document.getElementById('sumMonth');
var bgColor = [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ];
var boColor = [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ];
const sbkChart = new Chart(sbk, {
    type: 'bar',
    data: {
        labels: [
          <?php foreach ($sumByKat as $kat){
                    echo "'{$kat->getKategorie()}',";
                    }

          ?>
        ],
        datasets: [{
            label: '€',
            data: [
              <?php foreach ($sumByKat as $sum){
                    echo "'{$sum->getSumKat()}',";
                    }

              ?>
            ],
            backgroundColor: bgColor,
            borderColor: boColor,
            borderWidth: 1,
        }]
    },
    options: {
        responsive: true,
        tooltips: {
          displayColors: false
        },
        plugins: {
            legend: {
                display: false,
            }
        }
    }
});

const monthSumChart = new Chart(sM, {
    type: 'line',
    data: {
        labels: [
          <?php foreach ($sumMonth as $mon){
                    echo "'{$mon->getMonat()}',";
                    }
          ?>
        ],
        datasets: [{
            label: '€',
            data: [
              <?php foreach ($sumMonth as $sum){
                    echo "'{$sum->getSumme()}',";
                    }
              ?>
            ],
            backgroundColor: bgColor,
            borderColor: boColor,
            borderWidth: 1,
            fill: true,
            stepped: false,
            tension: 0.5
        }]
    },
    options: {
        responsive: true,
        tooltips: {
          displayColors: false
        },
        plugins: {
            legend: {
                display: false,
            }
        }
    }
});
</script>
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>