<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="container-fluid paddingBottom">
    <div class="right py-2">
      <div class="w3-dropdown-click">
        <button onclick="getMonth()" class="btn btn-primary">Monat/Jahr</button>
        <div id="monat" class="w3-dropdown-content w3-bar-block w3-border text-center">
          <a href="<?php echo App::getBaseUrl()."/finanzen/haushaltskasse/"; ?>" class="w3-bar-item w3-button">-</a>
        <?php foreach (\Util\Datum::getDateRange() as $date): ?>
          <a href="<?php echo App::getBaseUrl()."/finanzen/haushaltskasse/datum/".$date->format('Y-m'); ?>" class="w3-bar-item w3-button"><?php echo $date->format('m/y')."\n";?></a>
        <?php endforeach; ?> 
        </div>
      </div>
    </div> 
    <table class="table table-striped mb-0 text-center">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Wer</th>
          <th scope="col">Wann</th>
          <th scope="col">+/-</th>
          <th scope="col">Stand</th>
        </tr>
      </thead>
      <tbody>
      <?php $i=count($data)+1; foreach ($data as $ausgabe): $i--;?>
        <tr>
          <th scope="row"><?php /* echo */ $ausgabe->getId(); echo $i;?></th>
          <td><?php echo $ausgabe->getWer(); ?></td>
          <td><?php echo date("d.m.y",strtotime($ausgabe->getDatum())); ?></td>
          <?php if ($ausgabe->getWomit() == 'lend') {
              if ($ausgabe->getWieviel() > '0') {
                echo "<td style='color:green'>{$ausgabe->getWieviel()} &#8364;</td>";
              } else {
                echo "<td style='color:red'>{$ausgabe->getWieviel()} &#8364;</td>";
              }            
          } else {
            echo "<td>{$ausgabe->getWieviel()} &#8364;</td>";
          }; ?>
          <td><?php echo $ausgabe->getStand(); ?> &#8364;</td>
        </tr>
      <?php endforeach; ?>
      </tbody>      
    </table> 
    <div class="center">
      <div class="center fs-6" style="color:red">rot = geliehen</div>
      <div class="center fs-6" style="color:green">grün = zurückgezahlt</div>
    </div>
    <nav aria-label="kasse" class="py-3">
      <ul class="pagination pagination-sm justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- End page content -->

<!-- Footer -->

<!-- Link und auswahl zur doppel child modal mit versch. Formularen
 -->
<!-- Modal -->
<footer class="footer mt-auto py-3 bgTop">
<div class="container-fluid">
      <div class="right">
        <a href="#add" data-target="#id" data-toggle="modal" class="lift" onclick="document.getElementById('choose').style.display='block'">
          <i class="fas fa-plus-circle add lift"></i>
        </a>       
      </div>
      <div id="choose" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content w3-card-4 w3-animate-zoom">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Haushaltskasse</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('choose').style.display='none'"></button>
                </div>
                <div class="modal-body">
                <div class="text-center">Abrechnen oder pers. Konto ausgleichen?
                  <div class="row justify-content-md-center">
                      <div class="col p-5">
                        <a href="#add" data-target="#id" data-toggle="modal" class="" onclick="document.getElementById('add').style.display='block'" onmouseup="document.getElementById('choose').style.display='none'">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/out.png" alt="abrechnen" class="img-fluid" >
                        </a>                        
                      </div>
                      <div class="col p-5">
                        <a href="#add" data-target="#id" data-toggle="modal" class="" onclick="document.getElementById('balance').style.display='block'" onmouseup="document.getElementById('choose').style.display='none'">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/money-transfer.png" alt="einzahlen"  class="img-fluid" >
                        </a>                          
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </div>
      <div id="balance" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content w3-card-4 w3-animate-zoom">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Haushaltskasse</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('balance').style.display='none'"></button>
                </div>
                <div class="modal-body">
                  <div class="">
                    <div class="justify-content-md-center">
                      <form id="balanceForm" class="addForm" method="post">
                        <input type="hidden" name="whichForm" value="balance">
                        <input type="hidden" name="uid" value="<?php echo $_SESSION['userId']; ?>">
                        <input type="hidden" name="wer" value="<?php echo $_SESSION['userName']; ?>">
                        <input type="hidden" name="konto" value="<?php echo $konto->getKonto(); ?>">
                        <input type="hidden" name="datum" type="date" value="<?php echo date("Y-m-d"); ?>">
                        <input type="hidden" name="stand" value="<?php echo $stand->getStand(); ?>">
                        <input type="hidden" name="lend" value="<?php echo $konto->getLend(); ?>">
                        <div class="lh-base pb-3">
                            Haushaltskasse aktuell: <b><?php echo $stand->getStand(); ?>&#8364;</b><br>
                            pers. Kontostand: <b><?php echo $konto->getKonto(); ?>&#8364;</b><br>
                        </div>
                        <div class="lh-sm">
                            <?php
                              echo \Util\Tops::calKonto($stand->getStand(), $konto->getKonto())['text'];                              
                            ?>
                        </div>
                        <div class="py-4" >
                            Betrag: 
                            <input type="number" name="wieviel" id="wieviel" max="<?php echo \Util\Tops::calKonto($stand->getStand(), $konto->getKonto())['max']; ?>" 
                            value="<?php echo \Util\Tops::calKonto($stand->getStand(), $konto->getKonto())['val']; ?>" class="form-control" step="0.5" required <?php echo \Util\Tops::calKonto($stand->getStand(), $konto->getKonto())['show']; ?> >
                        </div>
                      <div style="overflow:auto;">
                        <div style="float:right;">
                        <button type="reset" class="btn btn-secondary" id="close" onclick="document.getElementById('balance').style.display='none'">abbrechen</button>
                        <button type="submit" class="btn btn-primary" id="submit" <?php echo \Util\Tops::calKonto($stand->getStand(), $konto->getKonto())['show']; ?> >absenden</button>
                        </div>
                      </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </div>
      <div id="add" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content w3-card-4 w3-animate-zoom">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Haushaltskasse</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('add').style.display='none'"></button>
                </div>
                <div class="modal-body">
                <form id="addForm" class="addForm" method="POST">
                  <input type="hidden" name="whichForm" value="add">
                  <input type="hidden" name="wer" value="<?php echo $_SESSION['userName']; ?>">
                  <input type="hidden" name="uid" value="<?php echo $_SESSION['userId']; ?>">
                  <input type="hidden" name="konto" value="<?php echo $konto->getKonto(); ?>">
                  <input type="hidden" name="stand" value="<?php echo $stand->getStand(); ?>">
                  <input type="hidden" name="lend" value="<?php echo $konto->getLend(); ?>">
                  <div class="tab">Wann:
                    <p><input type="date" name="datum" class="form-control" value="<?php echo date("Y-m-d"); ?>" required></p>
                  </div>
                  <div class="tab">Wieviel:
                    <p><input type="number" name="wieviel" step="0.5" placeholder="  €" class="form-control" required></p>    
                    <p>Womit bezahlt?</p> 
                    <div>
                      <input type="radio" id="porte" name="womit" value="self" checked>
                      <label for="porte">eigenes Geld?</label>
                    </div>
                    <div>
                      <input type="radio" id="kasse" name="womit" value="kasse">
                      <label for="kasse">Haushaltskasse?</label>
                    </div>              
                  </div>
                  <div class="tab">Private Einkäufe he­r­aus­rech­nen?:
                    <p><input type="number" name="privat" step="0.5" placeholder="€" class="form-control" ></p>              
                  </div>
                  <div class="tab">wo warst du einkaufen?
                    <div class="row justify-content-md-center">
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="wo" id="bae" value="1" >
                      <label for="bae">
                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/bakery.png" alt="Baecker" class="img-fluid" >
                      </label>
                      </div>
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="wo" id="fle" value="2">
                      <label for="fle">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/wurst.png" alt="Fleischer" class="img-fluid" >
                      </label>
                      </div>
                    </div>
<!--                     <div class="row">
                      <div>
                        <input type="text" name="wo" class="form-control" >
                      </div>
                    </div> -->
                  </div>
                  <!-- Circles which indicates the steps of the form: -->
                  <div style="text-align:center;margin-top:40px;">
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span>
                    
                  </div>
                  <hr>
                  <div style="overflow:auto;">
                    <div style="float:right;">
                    <button type="button" class="btn btn-secondary" id="prevBtn" onclick="nextPrev(-1)">back</button>
                    <button type="button" class="btn btn-primary" id="nextBtn" onclick="nextPrev(1)">Next</button>
                    </div>
                  </div>
                </form> 
                </div>
              </div>
            </div>

      </div>
</footer>
<!-- Begin script area -->
<script src="<?php echo App::getBaseUrl() ?>/skin/js/form.js"></script>
<script src="<?php echo App::getBaseUrl() ?>/skin/js/script.js"></script>
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>