<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">

<title>homeBuddy - Deine freundliche Haushaltshilfe</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="icon" type="image/x-icon" href="<?php echo App::getBaseUrl() ?>/skin/images/favicon.ico">
<link rel="icon" type="image/png" href="<?php echo App::getBaseUrl() ?>/skin/images/favicon.png" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo App::getBaseUrl() ?>/skin/images/favicon.png" sizes="96x96">
<link rel="stylesheet" href="<?php echo App::getBaseUrl() ?>/skin/css/w3.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
<link media="all" rel="stylesheet" type="text/css" href="<?php echo App::getBaseUrl() ?>/skin/css/bootstrap.css" />
<link media="all" rel="stylesheet" type="text/css" href="<?php echo App::getBaseUrl() ?>/skin/css/style.css" />
<body class="bg-light">
<!-- Top container -->
<div class="w3-bar w3-top bgTop w3-large smenu" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right">your Home Buddy beta 2.4</span>
</div>
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left mh shadow-sm" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="<?php echo App::getBaseUrl() ?>/skin/images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span>Hallo, <strong><?php echo $_SESSION['userName']; ?></strong></span><br>
      <a href="#" class="w3-bar-item w3-button w3-circle uicon"><i class="fa fa-envelope"></i>
        <span class="position-absolute translate-middle badge rounded-pill border border-light bg-danger" style="font-size: 0.8em" >
          3
          <span class="visually-hidden">unread messages</span>
        </span>
      </a>
      <a href="#" class="w3-bar-item w3-button w3-circle uicon"><i class="fa fa-user"></i></a>
      <a href="#" class="w3-bar-item w3-button w3-circle uicon"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-bar-block paddingBottom">
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a> -->
    <a href="<?php echo App::getBaseUrl() ?>/" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw iconWidth"></i>Dashboard</a>
    <hr>
    <a href="<?php echo App::getBaseUrl() ?>/notes/" class="w3-bar-item w3-button w3-padding"><i class="fas fa-sticky-note iconWidth"></i>Notizen</a>
    <a href="<?php echo App::getBaseUrl() ?>/todo/" class="w3-bar-item w3-button w3-padding"><i class="fas fa-tasks iconWidth"></i>toDo</a>
    <hr>
    <div class="w3-bar-item w3-button" onclick="finDrop()">
      <i class="fas fa-euro-sign iconWidth"></i>Finanzen <i class="fa fa-caret-down"></i></div>
      <div id="finDrop" class="w3-hide w3-white">
      <a href="<?php echo App::getBaseUrl() ?>/finanzen/" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-chart-line iconWidth"></i>Auswertung</a>
      <a href="<?php echo App::getBaseUrl() ?>/finanzen/haushaltskasse" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-wallet iconWidth"></i>Haushaltskasse</a>
      <a href="<?php echo App::getBaseUrl() ?>/finanzen/ausgaben" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-cash-register iconWidth"></i>Ausgaben allg.</a>
      <a href="<?php echo App::getBaseUrl() ?>/finanzen/frederico" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-shuttle-van iconWidth"></i>Frederico</a>
      </div>
    <hr>
    <div class="w3-bar-item w3-button" onclick="kitDrop()">
      <i class="fas fa-mug-hot iconWidth"></i>K&uuml;che <i class="fa fa-caret-down"></i></div>
      <div id="kitDrop" class="w3-hide w3-white">
      <a href="<?php echo App::getBaseUrl() ?>/kueche/" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-mug-hot iconWidth"></i>&Uuml;bersicht</a>
      <a href="<?php echo App::getBaseUrl() ?>/kueche/einkauf" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-shopping-cart iconWidth"></i>Einkauf</a>
      <a href="<?php echo App::getBaseUrl() ?>/kueche/rezepte" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-sync iconWidth"></i>Rezept Karusell</a>
      </div>
      <hr>
    <div class="w3-bar-item w3-button" onclick="wohDrop()">
      <i class="fas fa-laptop-house iconWidth"></i>Wohnung <i class="fa fa-caret-down"></i></div>
      <div id="wohDrop" class="w3-hide w3-white">
      <a href="<?php echo App::getBaseUrl() ?>/kueche/" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-chart-bar iconWidth"></i>&Uuml;bersicht</a>
      <a href="<?php echo App::getBaseUrl() ?>/kueche/einkauf" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-shower iconWidth"></i>Wasser</a>
      <a href="<?php echo App::getBaseUrl() ?>/kueche/rezepte" class="w3-bar-item w3-button w3-padding">&nbsp; &nbsp; &nbsp; &nbsp;<i class="fas fa-temperature-high iconWidth"></i>Heizung</a>
      </div>
    <hr>
    <a href="<?php echo App::getBaseUrl() ?>/" class="w3-bar-item w3-button w3-padding"><i class="fas fa-cog iconWidth"></i>Settings</a>
    <hr>
    <a href="<?php echo App::getBaseUrl() ?>/index/logout" class="w3-bar-item w3-button w3-padding"><i class="fa fa-power-off iconWidth"></i>Logout</a>
    <br>
    <br>
  </div>
  <footer class="navfooter mt-auto py-3 bgTop">
    <div class="container">
      &nbsp
    </div>
  </footer>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<div class="w3-main" style="margin-left:300px;margin-top:43px;">
  <!-- Header -->
  <header class="w3-container" style="padding-top:12px">
    <!-- <h5><b><i class="fa fa-dashboard"></i>Dashboard</b></h5> -->
  </header>

  <div class="w3-row-padding w3-margin-bottom dash w3-animate-top">
      <a href="<?php echo App::getBaseUrl() ?>/finanzen/haushaltskasse"> 
        <div class="w3-third dashbox bgDash1">    
          <div class="w3-container  w3-padding-16">
            <div class="left">
              Haushaltskasse: <br>
              Dein Kontostand: 
            </div>
            <div class="right">
              <?php foreach (\Util\Tops::getTopStand() as $stand): ?>      
                <div class="right"><?php echo $stand->getStand() ?> &#8364;<br></div><br clear="all" />             
              <?php endforeach; ?> 
              <?php foreach (\Util\Tops::getTopKonto($_SESSION['userId']) as $konto): ?>      
                <div class="right"><?php echo $konto->getKonto() ?> &#8364;<br></div><br clear="all" />             
              <?php endforeach; ?>           
            </div>
          </div>  
          
        </div>
      </a>
      <a href="<?php echo App::getBaseUrl() ?>/kueche/einkauf"> 
        <div class="w3-third dashbox bgDash3">    
          <div class="w3-container bgDash3 w3-padding-16">
            <div class="left">
              Einkauflisten vorhanden:
            </div>
            <div class="right">
              2
            </div><br clear="all" /> 
          </div>      
        </div>
      </a> 
      <a href="<?php echo App::getBaseUrl() ?>/finanzen/ausgaben"> 
        <div class="w3-third dashbox bgDash2">    
          <div class="w3-container bgDash2 w3-padding-16">
              <?php foreach (\Util\Tops::getTopAusgaben() as $topAusgabe): ?>                
                <div class="left"> <?php echo $topAusgabe->getWer() ?></div>
                <div class="right"><?php echo $topAusgabe->getSumAusgaben()." &#8364;<br>"; ?> </div><br clear="all" />             
              <?php endforeach; ?> 
          </div>      
        </div>
      </a>
  </div>
