<div class="pagin py-3">
        <nav aria-label="pagin" class="">
                <ul class="pagination pagination-sm shadow-sm">
                        <li class="page-item <?php if ($pagination->getCurrPage() <= 1){ echo "disabled"; } ?>">
                                <a class="page-link" href="<?php if ($pagination->getCurrPage() <= 1) {echo '#';} else {echo "?page=".$pagination->getPrevPage();} ?>" rel="prev" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                </a>
                        </li>
                        <?php for ($i=1; $i <= $pagination->getPages(); $i++): ?>
                        <li class="page-item <?php if($pagination->getCurrPage() == $i || NULL) {echo 'active'; } ?>">
                                <a class="page-link" href="?page=<?= $i; ?>"> <?= $i; ?> </a>
                        </li>
                        <?php endfor; ?>          
                        <li class="page-item <?php if ($pagination->getCurrPage() >= $pagination->getPages()){ echo "disabled"; } ?>">
                                <a class="page-link" href="<?php if ($pagination->getCurrPage() >= $pagination->getPages()) {echo '#';} else {echo "?page=".$pagination->getNextPage();} ?>" rel="next" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                </a>
                        </li>
                </ul>
        </nav>
</div>