<div class="pagin py-3">
        <nav aria-label="pagin" class="">
                <ul class="pagination pagination-sm shadow-sm">
                        <?php if ($paginator->getPrevUrl()): ?>
                                <li class="page-item"><a class="page-link" href="<?php echo $paginator->getPrevUrl(); ?>">&laquo;</a></li>
                        <?php endif; ?>

                        <?php foreach ($paginator->getPages() as $page): ?>
                                <?php if ($page['url']): ?>
                                <li <?php echo $page['isCurrent'] ? 'class="page-item active"' : ''; ?>>
                                        <a class="page-link" href="<?php echo $page['url']; ?>"><?php echo $page['num']; ?></a>
                                </li>
                                <?php else: ?>
                                <li class="disabled page-item"><span class="page-link"><?php echo $page['num']; ?></span></li>
                                <?php endif; ?>
                        <?php endforeach; ?>

                        <?php if ($paginator->getNextUrl()): ?>
                                <li class="page-item"><a class="page-link" href="<?php echo $paginator->getNextUrl(); ?>">&raquo;</a></li>
                        <?php endif; ?>
                </ul>
        </nav>
</div>