<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="container-fluid paddingBottom">
    Willkommen bei deinem Home Buddy
  </div>
</div>
<footer class="footer mt-auto py-3 bgTop">
    <div class="container">
      &nbsp
    </div>
</footer>
<!-- End page content -->
<!-- Begin Footer -->
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>