<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="w3-row-padding paddingBottom">
    <div class="w3-col m4 l4 py-2">
      <div class="card h-200 shadow-sm">
        <img src="https://www.kochtrotz.de/wp-content/uploads/2021/04/ofen-spitzkohl-5-2-300x200.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
    <div class="w3-col m4 l4 py-2">
      <div class="card h-200 shadow-sm">
        <img src="https://www.wunderkessel.de/media/leckerer-klossauflauf.18618/full?lightbox=1&last_edit_date=0" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
    <div class="w3-col m4 l4 py-2">
      <div class="card h-200 shadow-sm">
        <img src="https://images.lecker.de/come-together-gulasch-f10486301,id=a2f0dcca,b=lecker,w=590,h=442,cg=c.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        </div>
        <div class="card-footer">
          <small class="text-muted">Last updated 3 mins ago</small>
        </div>
      </div>
    </div>
  </div>
</div>
<footer class="footer mt-auto py-3 bgTop">
    <div class="container">
      &nbsp
    </div>
</footer>
<!-- End page content -->
<!-- Begin Footer -->
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>