<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/head.inc.phtml'); ?>
<!-- !PAGE CONTENT! -->
  <div class="container-fluid paddingBottom">
    <div class="right py-2">
      <div class="w3-dropdown-click">
        <button onclick="getMonth()" class="btn btn-primary">Monat/ Jahr</button>
        <div id="monat" class="w3-dropdown-content w3-bar-block w3-border">
        <?php foreach (\Util\Datum::getDateRange() as $date): ?>
          <a href="<?php echo App::getBaseUrl().$_SERVER['REQUEST_URI']."/Datum/".$date->format('Y-m'); ?>" class="w3-bar-item w3-button"><?php echo $date->format('m/y')."\n";?></a>
         <!-- check ob schon filter/datum gesetzt ist sonst > http://localhost:3000/finanzen/haushaltskasse/filter/2021-09/filter/2021-04 
        funktion check filter
        tabellenkopf dynamisch über ausgabe array index
        --> 
      

        <?php endforeach; ?> 
        </div>
      </div>
    </div>

    <table class="table table-striped mb-0">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Wer</th>
          <th scope="col">Wann</th>
          <th scope="col">Wieviel</th>
          <th scope="col">Stand</th>
        </tr>
      </thead>
      <tbody>
      <?php var_dump($kasse); ?>
      <?php foreach ($kasse as $ausgabe): ?>
        <tr>
          <th scope="row"><?php echo $ausgabe->getId(); ?></th>
          <td><?php echo $ausgabe->getWer(); ?></td>
          <td><?php echo $ausgabe->getDatum(); ?></td>
          <td><?php echo $ausgabe->getWieviel(); ?></td>
          <td><?php echo $ausgabe->getStand(); ?></td>
        </tr>
        <?php endforeach; ?>
      </tbody>      
    </table>
  </div>
</div>

<!-- End page content -->

<!-- Footer -->


<!-- Modal -->
<footer class="footer mt-auto py-3 bgTop">
<div class="container-fluid">

      <div class="right">
        <a href="#add" data-target="#id" data-toggle="modal" class="lift" onclick="document.getElementById('add').style.display='block'">
          <i class="fas fa-plus-circle add lift"></i>
        </a>       
      </div>
      <div id="add" class="w3-modal ">
            <div class="modal-dialog " >
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="modalTitle">Haushaltskasse</h5>
                  <button type="button" class="btn-close" onclick="document.getElementById('add').style.display='none'"></button>
                </div>
                <div class="modal-body">
                <form id="addForm" class="addForm" method="POST">
                  <input type="hidden" name="wer" value="<?php echo $_SESSION['userName']; ?>">
                  <input type="hidden" name="uri" value="<?php echo $_SERVER['REQUEST_URI']; ?>">
                  <!-- One "tab" for each step in the form: -->
                  <div class="tab">abrechnen oder einzahlen?
                    <div class="row justify-content-md-center">
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="inorout" id="abr" value="-" checked required >
                      <label for="abr">
                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/out.png" alt="abrechnen" class="img-fluid" >
                      </label>
                      </div>
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="inorout" id="einz" value="+">
                      <label for="einz">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/in.png" alt="einzahlen"  class="img-fluid" >
                      </label>
                      </div>
                    </div>
                  </div>
                  <div class="tab">Wann:
                    <p><input type="date" name="datum" class="form-control" value="<?php echo date("Y-m-d"); ?>" required></p>
                  </div>
                  <div class="tab">Wieviel:
                    <p><input type="number" name="wieviel" step="0.5" placeholder="  €" class="form-control" required></p>    
                    <p>Womit bezahlt?</p> 
                    <div>
                      <input type="radio" id="porte" name="womit" value="self" checked>
                      <label for="porte">eigenes Geld?</label>
                    </div>
                    <div>
                      <input type="radio" id="kasse" name="womit" value="kasse">
                      <label for="kasse">Haushaltskasse?</label>
                    </div>              
                  </div>
                  <div class="tab">Private Einkäufe he­r­aus­rech­nen?:
                    <p><input type="number" name="privat" step="0.5" placeholder="€" class="form-control" ></p>              
                  </div>
                  <div class="tab">wo warst du einkaufen?
                    <div class="row justify-content-md-center">
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="wo" id="baecker" value="Baecker" required >
                      <label for="baecker">
                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/bakery.png" alt="Bäcker" class="img-fluid" >
                      </label>
                      </div>
                      <div class="col px-5">
                      <input type="radio" class="sr-only" name="wo" id="fleischer" value="fleischer">
                      <label for="fleischer">
                          <img src="<?php echo App::getBaseUrl() ?>/skin/images/haushaltskasse/wurst.png" alt="Fleischer"  class="img-fluid" >
                      </label>
                      </div>
                    </div>
                    <div class="row">
                      <div>
                        <input type="text" name="wo" id="wo" class="form-control">
                      </div>
                    </div>
                  </div>
                  <!-- Circles which indicates the steps of the form: -->
                  <div style="text-align:center;margin-top:40px;">
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span>
                    <span class="step"></span> 
                  </div>
                  <hr>
                  <div style="overflow:auto;">
                    <div style="float:right;">
                    <button type="button" class="btn btn-secondary" id="prevBtn" onclick="nextPrev(-1)">back</button>
                    <button type="button" class="btn btn-primary" id="nextBtn" onclick="nextPrev(1)">Next</button>
                    </div>
                  </div>
                </form> 
                </div>
              </div>
            </div>

      </div>
</footer>
<!-- Begin script area -->
<script src="<?php echo App::getBaseUrl() ?>/skin/js/form.js"></script>
<script src="<?php echo App::getBaseUrl() ?>/skin/js/script.js"></script>
<?php   require_once($_SERVER['DOCUMENT_ROOT'].'/template/foot.inc.phtml'); ?>